### ISSUE TITLE
Sharing the validation files of SDD

### ISSUE THREAD

**Issue by os1a** [nachiket92/P2T#1]
Hi,

Could you please share with me the validation files of the TrajNet benchmark for SDD.

The website seems broken and I have only train and test file.

Thanks,

**Comment by nachiket92** [comment]
Hi, sorry for the late response. The raw annotation files for SDD can be downloaded from this webpage. 
[https://cvgl.stanford.edu/projects/uav_data/](https://cvgl.stanford.edu/projects/uav_data/
)
Note that as per prior work (SoPhie, MATF, CF-VAE), we use all tracks in the raw annotation files including skateboarders, bicyclists, golf carts, with the scenes split into train, val and test sets according to the TrajNet benchmark.  This is what the authors of SoPhie recommended in our email correspondence. The TrajNet benchmark itself contains a subset of trajectories that are all pedestrians and represents an easier test setting in my experience. 

The train, val and test scenes have been listed in table 1 of the paper. 

Hope this helps!

**Comment by os1a** [comment]
Thanks for your respond.

Which table 1 you are referring to, where I can find train/test/valid splits.

Best,

**Comment by nachiket92** [comment]
My bad, the updated version on arXiv doesn't have the table. It's in v1, but I have copied it here for reference. 

![SDD_splits](https://user-images.githubusercontent.com/19274071/121782682-ae356a80-cb5f-11eb-86bf-92e17b516a1f.JPG)

**Comment by nachiket92** [comment]
I have additionally shared the pre-processed files for the SDD train/val/test sets. Hope this helps. Closing this issue for now.

**Comment by centiLinda** [comment]
Just want to point out a typo here. There's no little4 and quad4. For the test set it should be little: 0-3 and quad: 0-3.

In case anyone is confused.
