### ISSUE TITLE
SDD data split in Table I

### ISSUE THREAD

**Issue by tedhuang96** [nachiket92/P2T#10]
Hello Nachiket,

Thank you for your wonderful work and open-source code! I am struggling to find SDD data split provided by trajnet, which seems to be expired. Based on the discussion in #2, may I confirm the data files in https://github.com/nachiket92/P2T/tree/main/data/sdd correspond to the data split of Table I, which is essentially the trajnet split for SDD? And if we want to use the split used in PECNet, we have to process the data provided by PECNet github repo, is that true?

Best,

Zhe Huang

_Originally posted by @tedhuang96 in https://github.com/nachiket92/P2T/issues/2#issuecomment-1105967142_

**Comment by nachiket92** [comment]
Hi Zhe, yes, that's correct. The preprocessed data provided corresponds to the data split in Table I. 
 
Table II uses tracks from the trajNet benchmark. This has the same train/val/test split of scenes. However it uses a subset of all tracks, primarily pedestrians. I believe the PECNet/Y-Net repo has this data. I can share my pre processed files as well. I see another issue here requesting them.

**Comment by nachiket92** [comment]
I have uploaded the data for Table II.

**Comment by tedhuang96** [comment]
I really appreciate your fast response! Have a great day!

**Comment by DelinquentLeon** [comment]
> Hi Zhe, yes, that's correct. The preprocessed data provided corresponds to the data split in Table I.
> 
> Table II uses tracks from the trajNet benchmark. This has the same train/val/test split of scenes. However it uses a subset of all tracks, primarily pedestrians. I believe the PECNet/Y-Net repo has this data. I can share my pre processed files as well. I see another issue here requesting them.

@nachiket92 hi,i wondered what are the 20 scenes used in PECNet,it is not mentioned in the repo, and the data before processing in PECNet is not accessed,could you please share me with the 20 scenes used in PECNet
