### ISSUE TITLE
Questions about SDD dataset

### ISSUE THREAD

**Issue by Alue111** [nachiket92/P2T#2]
Hello Nachiket,

I am working on trajectory forcasting modeling and I am impressed with your model. I have questions about the SDD dataset. The raw SDD data is available on the website, but I am not sure that my short trem data processing is the same way as yours. The frames are sampled at FPS = 2.5 and for each pedstrains in each videos, I intercept the first 8s (3.2s observation and 4.8s prediction) of each pedstrain trajectories.  As shown in the code below. I want to know if this process is the same as yours. 
Thank you for your time, and I look forward to hearing from you.

--Lue Li

`
import numpy as np
import pathlib
import pickle
from tqdm import tqdm
import random

labels_object = {'\"Pedestrian\"': 0,'\"Skater\"': 1,'\"Biker\"': 2,'\"Car\"': 3,'\"Cart\"': 3,'\"Bus\"': 3}
SDD_RAW_DIR = pathlib.Path('../datasets/SDD')

def get_annotation(data_dir):

    global labels_object
    print(data_dir)
    with open(data_dir, 'r') as f_a:
        lines = []
        for line in f_a:
            line = line.strip().split(" ")
            line = [int(line[5]), int(line[0]), (float(line[2]) + float(line[4])) / 2.0,
                    (float(line[1]) + float(line[3])) / 2.0, labels_object[line[9]]]
            # frame object_id x y type
            if (line[4]== 0):
                lines.append(np.asarray(line))
    lines = np.stack(lines)
    return lines

def process_data(file_dir,setname):

    scene_dir = file_dir / 'label.jpg'
    data_a = get_annotation(file_dir/'annotations.txt', scene_dir)
    all_obj = np.unique(data_a[:, 1])
    all_data = None
    for obj in all_obj:
        obj_allframe = data_a[(data_a[:,1]==obj), :]
        mask = np.arange(0, obj_allframe.shape[0],12)
        obj_sampleframe = obj_allframe[mask,:]
        if (obj_sampleframe.shape[0] < 20):
            continue
        index = 0
        if (all_data is None):
            all_data = obj_sampleframe[index: index+20,:]
        else:
            all_data = np.concatenate((all_data, obj_sampleframe[index: index+20,:]))
    human_num = all_data.shape[0]
    print("human_num = {}".format(human_num))
    path = '../trajnet_process_onlyped/' +setname + '/stanford/' + str(file_dir.parents[0].name) + '_' + str(file_dir.name)[-1] + '.txt'
    np.savetxt(path,all_data,fmt='%.01f')
    return human_num

if __name__ == '__main__':

      train_set = {'bookstore': [0, 1, 2, 3], 'coupa': [3], 'deathCircle': [0, 1, 2, 3, 4], 'gates': [0,1,3,4,5,6,7,8],
                 'hyang': [4, 5, 6, 7, 9], 'little': [], 'nexus': [0, 1, 2, 3, 4, 7, 8, 9], 'quad': []}
    test_set = {'bookstore': [], 'coupa': [0, 1], 'deathCircle': [], 'gates': [2],
                'hyang': [0, 1, 3, 8], 'little': [0, 1, 2, 3], 'nexus': [5, 6], 'quad': [0, 1, 2, 3]}
    # validation_set = {'bookstore': [4, 5, 6], 'coupa': [2], 'deathCircle': [], 'gates': [0],
    #                   'hyang': [2, 10, 11, 12, 13, 14], 'little': [], 'nexus': [10, 11], 'quad': []}
    data_setsplit = [train_set, test_set]
    set_dir = {}
    set_name = {0: 'train', 1: 'test'}
    for i, setdir in enumerate(data_setsplit):
        for key, value in setdir.items():
            if value == []:
                continue
            for idx in value:
                video_num = 'video' + str(idx)
                set_dir.setdefault(set_name[i], []).append(SDD_RAW_DIR / key / video_num)
    print(set_dir)
    for setname, setdir in set_dir.items():
        total_human = 0
        for file_dir in tqdm(setdir, desc='Process ' + setname):
            print(file_dir)
            human_num = process_data(file_dir,setname)
            total_human += human_num
        print('{} human num = {}'.format(setname,total_human))
`

**Comment by nachiket92** [comment]
Thank you for your interest in the work.  We use all tracks in the SDD raw files, including skateboarders, bicyclists and golf carts. 
Also, since several tracks are longer than 8 sec, they yield several 8 sec snippets that serve as multiple train and test instances. 
The train/val/test sets correspond to different scenes in SDD, listed in table 1 of the paper. 

Hope this helps!

**Comment by Alue111** [comment]
Thank you very much for your reply!

**Comment by tedhuang96** [comment]
Hello Nachiket,

Thank you for your wonderful work and open-source code! I want to comment on this question because I am struggling to find SDD data split provided by trajnet, which seems to be expired. Based on the discussion here, may I confirm the data files in https://github.com/nachiket92/P2T/tree/main/data/sdd correspond to the data split of Table I, which is essentially the trajnet split for SDD? And if we want to use the split used in PECNet, we have to process the data provided by PECNet github repo, is that true?

Best,

Zhe Huang
