### ISSUE TITLE
Data Processing of SDD

### ISSUE THREAD

**Issue by HRHLALALA** [nachiket92/P2T#3]
Hi, thanks for the excellent work. In order to make a fair experimental environment for my research as yours, may I ask how you dealt with those instabilities in SDD such as lost detection, occlusion? Also, did you do any data cleaning, e.g. removing the static pedestrians? Any help will be appreciated!

**Comment by nachiket92** [comment]
Hi, for every track, we discarded the timestamps for which the tracks were lost from the train/val/test sets. The raw annotation files have a flag indicating lost tracks. We used this for filtering. We didn't remove static agents if they were visible, since these are still valid data points.

**Comment by HRHLALALA** [comment]
Thanks for the reply.  It's really helpful.
