### ISSUE TITLE
image of '/data/nuscenes/dataset/prediction_raster_maps/images200_50m' 

### ISSUE THREAD

**Issue by lylyjy** [nachiket92/P2T#5]
It seems that '/data/nuscenes/dataset/prediction_raster_maps/images200_50m' does not exist.

**Comment by L4zyy** [comment]
I met the same problem and it turns out that you need to make prediction_raster_maps folder manually (at least in my case) to get this work.

**Comment by nachiket92** [comment]
Yes, please create the folder and run preprocess_data.py. I'll add a readme file with installation and usage instructions shortly.

**Comment by Kay1794** [comment]
Hi all,

I know the issue has been closed but I was wondering where I could find the preprocess_data.py. Thank you so much!
