### ISSUE TITLE
Questions about finetune_traj_generator and multiprocessing

### ISSUE THREAD

**Issue by L4zyy** [nachiket92/P2T#6]
Hi, Thank you for your great works! I plan to retrain your model as my baseline. However I got some trouble when I running your code.  When I running finetune_traj_generator.py, the program seems to hang in Kmeans methods for a long time even when I use 1% of the data. I wonder how long will it takes you to run finetune_traj_generator.py and is this function shoud be slow or something goes wrong in my operations. Also, I didn't find pytorch DDP in your codebase, do you use other methods for data parallel or you just train your model with single GPU?

**Comment by nachiket92** [comment]
The code was implemented and tested with a single GPU. K-means is implemented using Scikit-learn, on CPU. Multiprocessing does speed up training in my experience. You could try doing this without multiprocessing and check if it's faster.

**Comment by L4zyy** [comment]
The program did hang for a very long time. After I remove multiprocessing related code, theK-means function works fine. Thank for the quick and helpful reply ^ ^
