### ISSUE TITLE
Questions about processed_data

### ISSUE THREAD

**Issue by FCKOP** [nachiket92/P2T#7]
Hi, Thank you for your great works!  But I have a few questions about data processing：
1、The mat files include 2 elements: D and tracks. What is the value of D[idx ,3] means? This value is not used in your code. (I guess it stands for the object label)
2、How do you ensure that there is a trajectory of the corresponding length？For example, when setting the historical trajectory to 8 frames, your approach is to take 8 steps forward, but these data may not be complete. Therefore, I guess from the distribution of your data (D and tracks) that your D may only contain a part of the middle frame to ensure this, but this will result in not using all the tracks.
Thanks!

**Comment by nachiket92** [comment]
Both good points.

1) I do extract the object label for SDD. The original plan was to have separate reward maps based on object category (pedestrians and vehicles could have different goals/path preferences), but I didn't really get around to this. Might be worth trying out. 

2) You're right, I discard the ends of tracks in SDD where we don't have 4.8s of the future trajectory. One workaround could be to just compute metrics for whatever track length is available at the end (say 3s). But this would drive the MinFDE values lower without really solving the problem.

**Comment by FCKOP** [comment]
Thanks! Your answer helps a lot. By the way, what does the label(0,1,2)  about object category stands for?
Another question is what is the value means in track file [1:3], I used it as an (x, y) coordinate at first, and then I saw you multiply a transformation matrix about theta. Why rotate coordinates based on theta?

**Comment by nachiket92** [comment]
0: Bicyclist, 1:Pedestrian, 2: Skateboarder, 3: Golf cart.

The tracks are translated and rotated so that the origin is at the agent being predicted and the x-axis is along their instantaneous direction of motion.

**Comment by FCKOP** [comment]
Thanks for the reply！
