### ISSUE TITLE
nuScenes data preprocess code

### ISSUE THREAD

**Issue by Kay1794** [nachiket92/P2T#8]
I am not sure if I miss something since I am not able to find the preprocess_data.py for nuScenes in the repo which mentioned in issue #5

**Comment by nachiket92** [comment]
Ah, my bad. The name of the script was changed. It's 'extract_ns_maps.py'

**Comment by Kay1794** [comment]
> Ah, my bad. The name of the script was changed. It's 'extract_ns_maps.py'

Thank you so much for your quick reply! It works well :)
